version: '3.9'

services:
 store-dev-db:
  image: postgres:latest
  env_file:
      - .env.dev
#  environment:
#    - POSTGRES_USER=admin
#    - POSTGRES_PASSWORD=admin1234
#    - POSTGRES_DB=listings
  ports:
    - "5433:5432"
  restart: always
  volumes:
    - database-dev-data:/var/lib/postgresql/data/

 store-test-db:
  image: postgres:latest
  env_file:
    - .env.test
#  environment:
#    - POSTGRES_USER=admin
#    - POSTGRES_PASSWORD=admin1234
#    - POSTGRES_DB=users
  ports:
    - "5434:5432"
  restart: always
  volumes:
    - database-test-data:/var/lib/postgresql/data/

volumes:
   database-test-data:
   database-dev-data: